### ISSUE TITLE
Aanmaken startpagina

### ISSUE THREAD

**Issue by IanWanzeele** [Hidetsugu666/Warcraft.github.io#1]
Startpagina maken met basic inhoud (Warcraft):
-Head
-Body
-Footer
-Bepalen layout startpagina
Taak verdeling wordt ook  gemaakt

**Comment by IanWanzeele** [comment]
Positionering is nog niet top

**Comment by Nicolas-Goemanne** [comment]
@turbello  Is dit aangepast? Mag dit naar de done pile
