### ISSUE TITLE
Team bespreking

### ISSUE THREAD

**Issue by Nicolas-Goemanne** [Hidetsugu666/Warcraft.github.io#5]
-Kleur identiteit 
-Opmaak
-Verdeling
-Inhoud & documentatie bepalen

**Comment by Nicolas-Goemanne** [comment]
Discord - call - 25/1

**Comment by turbello** [comment]
[Notules Teambespreking.docx](https://github.com/Hidetsugu666/Warcraft.github.io/files/14036653/Notules.Teambespreking.docx)

**Comment by Nicolas-Goemanne** [comment]
Notulen - akkoord - voor mij goed

**Comment by IanWanzeele** [comment]
![Background](https://github.com/Hidetsugu666/Warcraft.github.io/assets/157576889/e9a25270-ce8c-4d1a-a9eb-4b5366721084)
![Horde_Logo](https://github.com/Hidetsugu666/Warcraft.github.io/assets/157576889/efa7eb07-6a33-43d6-b829-ac361893cd92)
![Illidan](https://github.com/Hidetsugu666/Warcraft.github.io/assets/157576889/4b42ed3e-5495-4fb6-9fcd-b17ada36124c)
![WoW_Logo](https://github.com/Hidetsugu666/Warcraft.github.io/assets/157576889/d0b4c5af-86c2-4959-9c4d-5c982809c1bb)

**Comment by IanWanzeele** [comment]
![Alliance_Logo](https://github.com/Hidetsugu666/Warcraft.github.io/assets/157576889/079c2b25-7a6f-4420-8b97-02506bada920)
