### ISSUE TITLE
Pagina Jonathan

### ISSUE THREAD

**Issue by turbello** [Hidetsugu666/Warcraft.github.io#8]

**Comment by turbello** [comment]
Worklist pagina:

- [x] Header Body Footer maken in basis formaat.
- [x] CSS code schrijven voor basic layout.
- [x] Afbeeldingen opzoeken
- [x] Afbeeldingen uploaden in juiste layout
- [x] 5 lijnen info met character

**Comment by turbello** [comment]
Wachten review voor merging naar main branche.

**Comment by turbello** [comment]
@ #12 Link naar Pull request

**Comment by Nicolas-Goemanne** [comment]
Ok - mag van mij naar main branch gemerged worden.
